### ISSUE TITLE
"comparators.h" not found during compilation

### ISSUE THREAD

**Issue by elfring** [Shardcached/libshardcache#12] opened 2015-09-03 14:26 UTC
I have cloned the current source code repository.

```
elfring@Sonne:~/Projekte/libshardcache/lokal> LANG=C make V=1
…
libtool: compile:  gcc -c -DHAVE_UINT64_T ../src/binheap.c  -fPIC -DPIC -o ./.libs/binheap.o
In file included from ../src/binheap.c:1:0:
../src/binheap.h:21:25: fatal error: comparators.h: No such file or directory
compilation terminated.
Makefile:75: recipe for target 'binheap.o' failed
…
```

How should this situation be fixed?
Do any parameters need to be adjusted for the software build process?

**Comment by xant** [comment] 2015-09-03 14:37
mmmm I don't understand how is it possible you are in libshardcache/lokal  and you find ../src/binheap.c which instead is something from libhl ... so it should be ../deps/.libs
anyway, at the moment building from a different directory is not supported ... I think it works if you just do 'make' from the top srcdir right?

support for external build system is something not on our todolist for now and surely won't be high priority unless there are specific needs.

Anyway patches are welcome!

**Comment by xant** [comment] 2015-09-03 14:43
ah ... btw from what I see, in this specific case of comparators.h, probably using doublequotes instead of angle brackets would make it work (but still ... I doubt the rest will build smoothly from an external build dir)

**Comment by elfring** [comment] 2015-09-03 14:44
The directory "libshardcache/lokal" is just the folder I cloned the source code repository to.
The document "INSTALL" contains the information that an ordinary make call should download and build all the dependencies. Do I overlook any setting here?

**Comment by xant** [comment] 2015-09-03 14:52
mmm... from what I see the gcc command is missing at least a -I../src flag ... do you have custom CFLAGS or LDFLAGS environment variable set?

**Comment by elfring** [comment] 2015-09-03 14:53
No custom build parameters

**Comment by xant** [comment] 2015-09-03 14:58
welll ... I can't see how CFLAGS gets changed then ... can I see the "objects: CFLAGS += ..." line in the generated Makefile for libhl? (in deps/libhl/build/Makefile)
It might be that recent changes in libhl to make use of autoconf broke the build on some systems.
Even though on all the systems I can try (including drone.io) it builds properly.

**Comment by biappi** [comment] 2015-09-03 15:01
cannot reproduce on my dev machine

https://gist.github.com/biappi/e25618d5d9f4ebe4983b

**Comment by elfring** [comment] 2015-09-04 12:13
Is [the file "comparators.h"](https://github.com/xant/libhl/blob/af4340ab4ec57a9278ae016d514fb5c284ad9645/src/comparators.h "Comparison interface") also installed on your development and test system?
How do you ensure that only the appropriate header file versions are reused by the software build system?

**Comment by biappi** [comment] 2015-09-04 12:29
the build script copies the include files vended by its dependencies in $TREE_ROOT/deps/.incs/, which is included with -I with an appropriate CFLAG.

[Copying the file](https://gist.github.com/biappi/e25618d5d9f4ebe4983b#file-gistfile1-txt-L246):
`../src/comparators.h -> /Users/willy/test/libshardcache/deps/.incs/comparators.h`

[Passing the include](https://gist.github.com/biappi/e25618d5d9f4ebe4983b#file-gistfile1-txt-L315):
`cc -Ideps/.incs`

it seems you're not compiling the project the way it's set up to.

to compile it in the supported way, please freshly clone the repository, and invoke `make` from the repository root, that should work. The build products will be placed in the build root.

note that during the first compilation, network is required as the build script automatically fetches its git-submodules dependencies from github.com as a convenience.

please tell us if you can't compile the project this way, possibly attaching a full build log.

**Comment by elfring** [comment] 2015-09-04 12:45
Build log:
```
elfring@Sonne:~/Projekte/libshardcache> LANG=C && git clone https://github.com/Shardcached/libshardcache.git test12 && cd test12 && make
Cloning into 'test12'...
remote: Counting objects: 8597, done.
remote: Total 8597 (delta 0), reused 0 (delta 0), pack-reused 8597
Receiving objects: 100% (8597/8597), 4.04 MiB | 1.24 MiB/s, done.
Resolving deltas: 100% (5802/5802), done.
Checking connectivity... done.
make[1]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps'
Submodule 'deps/libchash' (https://github.com/dgryski/libchash) registered for path 'deps/libchash'
Cloning into 'deps/libchash'...
remote: Counting objects: 165, done.
remote: Total 165 (delta 0), reused 0 (delta 0), pack-reused 165
Receiving objects: 100% (165/165), 29.81 KiB | 0 bytes/s, done.
Resolving deltas: 100% (93/93), done.
Checking connectivity... done.
Submodule path 'deps/libchash': checked out '2315d5f832031a8ab391bdba528afc88e209675f'
/home/elfring/Projekte/libshardcache/test12/deps
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/libchash'
gcc -c -fPIC  -DHAVE_UINT64_T chash.c -o chash.o
gcc -shared -Wl,-soname,libchash.so -o libchash.so.1.0 chash.o
ln -sf ./libchash.so.1.0 ./libchash.so.1
ln -sf ./libchash.so.1.0 ./libchash.so
ar -r libchash.a chash.o
ar: creating libchash.a
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/libchash'
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/libchash'
Installing libraries in /home/elfring/Projekte/libshardcache/test12/deps/.libs
'libchash.a' -> '/home/elfring/Projekte/libshardcache/test12/deps/.libs/libchash.a'
'libchash.so' -> '/home/elfring/Projekte/libshardcache/test12/deps/.libs/libchash.so'
'libchash.so.1' -> '/home/elfring/Projekte/libshardcache/test12/deps/.libs/libchash.so.1'
'libchash.so.1.0' -> '/home/elfring/Projekte/libshardcache/test12/deps/.libs/libchash.so.1.0'
Installing headers in /home/elfring/Projekte/libshardcache/test12/deps/.incs
'chash.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/chash.h'
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/libchash'                                                                                      
Submodule 'deps/libhl' (https://github.com/xant/libhl) registered for path 'deps/libhl'                                                                                     
Cloning into 'deps/libhl'...                                                                                                                                                
remote: Counting objects: 2842, done.
remote: Total 2842 (delta 0), reused 0 (delta 0), pack-reused 2842
Receiving objects: 100% (2842/2842), 1.54 MiB | 682.00 KiB/s, done.                                                                                                         
Resolving deltas: 100% (2057/2057), done.                                                                                                                                   
Checking connectivity... done.                                                                                                                                              
Submodule path 'deps/libhl': checked out '3f348b8b25c27bdda8b9969ee82315a62687f3a1'                                                                                         
/home/elfring/Projekte/libshardcache/test12/deps                                                                                                                            
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu                                                                                                     
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether make sets $(MAKE)... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for inttypes.h... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for strings.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for int16_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for size_t... yes
checking for ssize_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint8_t... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible realloc... yes
checking for working strcoll... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... no
checking whether pthreads work with -Kthread... no
checking whether pthreads work with -kthread... no
checking for the pthreads library -llthread... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking for gettimeofday... yes
checking for memchr... yes
checking for memmove... yes
checking for memset... yes
checking for stpcpy... yes
checking for strchr... yes
checking for strcspn... yes
checking for strdup... yes
checking for strerror... yes
checking for strpbrk... yes
checking for strrchr... yes
checking for strspn... yes
checking for strstr... yes
checking for strtol... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h
config.status: executing libtool commands
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/libhl/build'
./libtool --mode=compile gcc -c  -DHAVE_UINT64_T ../src/binheap.c -o ./binheap.o
libtool: compile:  gcc -c -DHAVE_UINT64_T ../src/binheap.c  -fPIC -DPIC -o ./.libs/binheap.o
In file included from ../src/binheap.c:1:0:
../src/binheap.h:21:25: fatal error: comparators.h: No such file or directory
compilation terminated.
Makefile:75: recipe for target 'binheap.o' failed
make[2]: *** [binheap.o] Error 1
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/libhl/build'
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/libhl/build'
Installing libraries in /home/elfring/Projekte/libshardcache/test12/deps/.libs
cp: cannot stat 'libhl.a': No such file or directory
cp: cannot stat 'libhl.so': No such file or directory
Installing headers in /home/elfring/Projekte/libshardcache/test12/deps/.incs
'../src/atomic_defs.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/atomic_defs.h'
'../src/avltree.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/avltree.h'
'../src/binheap.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/binheap.h'
'../src/bsd_queue.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/bsd_queue.h'
'../src/comparators.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/comparators.h'
'../src/fbuf.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/fbuf.h'
'../src/hashtable.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/hashtable.h'
'../src/linklist.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/linklist.h'
'../src/pqueue.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/pqueue.h'
'../src/queue.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/queue.h'
'../src/rbtree.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/rbtree.h'
'../src/rbuf.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/rbuf.h'
'../src/refcnt.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/refcnt.h'
'../src/rqueue.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/rqueue.h'
'../src/skiplist.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/skiplist.h'
'../src/trie.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/trie.h'
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/libhl/build'
/home/elfring/Projekte/libshardcache/test12/deps
Submodule 'deps/libiomux' (https://github.com/xant/libiomux) registered for path 'deps/libiomux'
Cloning into 'deps/libiomux'...
remote: Counting objects: 839, done.
remote: Total 839 (delta 0), reused 0 (delta 0), pack-reused 839
Receiving objects: 100% (839/839), 410.37 KiB | 0 bytes/s, done.
Resolving deltas: 100% (494/494), done.
Checking connectivity... done.
Submodule path 'deps/libiomux': checked out '825e9e54faf7ee55c5e682f2733882fe5008f661'
/home/elfring/Projekte/libshardcache/test12/deps
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/libiomux'
cc  -DHAVE_UINT64_T -fPIC -Isrc -Wall -Werror -Wno-parentheses -Wno-pointer-sign -DTHREAD_SAFE -g -O3 -DHAVE_EPOLL -c src/iomux.c -o src/iomux.o
cc  -DHAVE_UINT64_T -fPIC -Isrc -Wall -Werror -Wno-parentheses -Wno-pointer-sign -DTHREAD_SAFE -g -O3 -DHAVE_EPOLL -c src/bh.c -o src/bh.o
cc  -DHAVE_UINT64_T -fPIC -Isrc -Wall -Werror -Wno-parentheses -Wno-pointer-sign -DTHREAD_SAFE -g -O3 -DHAVE_EPOLL -c src/iomtee.c -o src/iomtee.o
ar -r libiomux.a src/*.o
ar: creating libiomux.a
cc -L. -pthread -shared src/*.o -o libiomux.so
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/libiomux'
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/libiomux'
Installing libraries in /home/elfring/Projekte/libshardcache/test12/deps/.libs
'libiomux.a' -> '/home/elfring/Projekte/libshardcache/test12/deps/.libs/libiomux.a'
'libiomux.so' -> '/home/elfring/Projekte/libshardcache/test12/deps/.libs/libiomux.so'
Installing headers in /home/elfring/Projekte/libshardcache/test12/deps/.incs
'src/iomux.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/iomux.h'
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/libiomux'
Submodule 'deps/siphash-c' (https://github.com/xant/siphash-c) registered for path 'deps/siphash-c'
Cloning into 'deps/siphash-c'...
remote: Counting objects: 135, done.
remote: Total 135 (delta 0), reused 0 (delta 0), pack-reused 135
Receiving objects: 100% (135/135), 27.15 KiB | 0 bytes/s, done.
Resolving deltas: 100% (59/59), done.
Checking connectivity... done.
Submodule path 'deps/siphash-c': checked out '8ac68e83d388ca4cd0fd8af4eef27ad6b4e1b11c'
/home/elfring/Projekte/libshardcache/test12/deps
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/siphash-c'
make -C src all
make[3]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/siphash-c/src'
gcc -c -o siphash.o siphash.c  -DHAVE_UINT64_T -I.
ar -r libsiphash.a *.o
ar: creating libsiphash.a
gcc -shared -o libsiphash.so siphash.o
/usr/bin/ld: siphash.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
siphash.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'libsiphash.so' failed
make[3]: *** [libsiphash.so] Error 1
make[3]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/siphash-c/src'
Makefile:18: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/siphash-c'
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/siphash-c'
Installing libraries in /home/elfring/Projekte/libshardcache/test12/deps/.libs
'src/libsiphash.a' -> '/home/elfring/Projekte/libshardcache/test12/deps/.libs/libsiphash.a'
cp: cannot stat 'src/libsiphash.so': No such file or directory
Installing headers in /home/elfring/Projekte/libshardcache/test12/deps/.incs
'src/siphash.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/siphash.h'
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/siphash-c'
Submodule 'deps/libut' (https://github.com/xant/libut.git) registered for path 'deps/libut'
Cloning into 'deps/libut'...
remote: Counting objects: 31, done.
remote: Total 31 (delta 0), reused 0 (delta 0), pack-reused 31
Unpacking objects: 100% (31/31), done.
Checking connectivity... done.
Submodule path 'deps/libut': checked out '36b678fee2212248687140a1847ab595d012d4c4'
/home/elfring/Projekte/libshardcache/test12/deps
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/libut'
cc  -DHAVE_UINT64_T -fPIC -Isrc -Wall -Werror -Wno-parentheses -Wno-pointer-sign -DTHREAD_SAFE -O3   -c -o src/ut.o src/ut.c
ar -r libut.a src/*.o
ar: creating libut.a
cc -L. -pthread -shared src/*.o -o libut.so
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/libut'
make[2]: Entering directory '/home/elfring/Projekte/libshardcache/test12/deps/libut'
Installing libraries in /home/elfring/Projekte/libshardcache/test12/deps/.libs
'libut.a' -> '/home/elfring/Projekte/libshardcache/test12/deps/.libs/libut.a'
'libut.so' -> '/home/elfring/Projekte/libshardcache/test12/deps/.libs/libut.so'
Installing headers in /home/elfring/Projekte/libshardcache/test12/deps/.incs
'src/ut.h' -> '/home/elfring/Projekte/libshardcache/test12/deps/.incs/ut.h'
make[2]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps/libut'
make[1]: Leaving directory '/home/elfring/Projekte/libshardcache/test12/deps'
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/kepaxos_log.o src/kepaxos_log.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/arc.o src/arc.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/shardcache_replica.o src/shardcache_replica.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/connections.o src/connections.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/arc_ops.o src/arc_ops.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/log.o src/log.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/connections_pool.o src/connections_pool.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/serving.o src/serving.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/counters.o src/counters.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/shardcache.o src/shardcache.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/shardcache_client.o src/shardcache_client.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/shardcache_node.o src/shardcache_node.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/messaging.o src/messaging.c
cc -Ideps/.incs  -DBUILD_INFO="" -fPIC -Isrc -Wall -Wno-parentheses -Wno-pointer-sign -fno-strict-aliasing -DSQLITE_THREADSAFE=1 -g -O3   -c -o src/kepaxos.o src/kepaxos.c
ar -r libshardcache.a src/*.o
ar: creating libshardcache.a
cc src/*.o -L. -ldl -pthread deps/.libs/libhl.a deps/.libs/libchash.a deps/.libs/libiomux.a deps/.libs/libsiphash.a -shared -o libshardcache.so
cc: error: deps/.libs/libhl.a: No such file or directory
Makefile:87: recipe for target 'shared' failed
make: *** [shared] Error 1
```

**Comment by biappi** [comment] 2015-09-04 12:51
oh.. this is really interesting:

`/usr/bin/ld: siphash.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC`

can you try passing CFLAGS="-fPIC" to make?

i will also open an issue to let make knows the sub-makefile failed (i cannot work on that immediately, tho)

**Comment by elfring** [comment] 2015-09-04 13:38
The command variant "make CFLAGS=-fPIC" is insufficient so far to fix the error message "/usr/bin/ld: siphash.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object" here.

**Comment by biappi** [comment] 2015-09-06 16:43
you're right, the flag was passed.

on a second, more calm, look at your build log it seems that libhl's libtool invocation is eating up the cflags:

`./libtool --mode=compile gcc -c  -DHAVE_UINT64_T ../src/binheap.c -o ./binheap.o`

it doesn't happen to me and i do not have much experience in using that autoconf suite. i guess there are some problems with the recent libhl patches.

it seems you are using a linux x86_64 box, i've tried your verbatim cmdline in a centos6 box and it works correctly. do you think there is something from your environment interfering?

**Comment by elfring** [comment] 2015-09-06 17:48
I have not got an explanation for the reported build failures so far.
Should the target "shared" be clarified by a separate issue?

**Comment by xant** [comment] 2016-03-09 15:16
I'm not able to reproduce this problem on any of the systems I have access to.
Please submit a patch or give me access to a system where I can debug the issue.
In the meanwhile I close this issue because there is no actionable

**Closed by xant** 2016-03-09 15:16 UTC
